### ISSUE TITLE
typo in Persian translation of `Full list`

### ISSUE THREAD

**Issue by ahmadalli** [reactivemanifesto/reactivemanifesto#105]
I couldn't find that translation in Persian translation file.
the right phrase is `لیست کامل` but in the Persian page, it's `لسیت کامل`
you can see the diff [here](https://www.diffchecker.com/YOeUcO1J)

**Comment by esfand-r** [comment]
I think you are referring to https://github.com/reactivemanifesto/website-manifesto/blob/master/conf/messages.fa . You could make a PR for a fix there. Cheers

**Comment by ahmadalli** [comment]
thanks. @esfand-r
