### ISSUE TITLE
Provide learning resources

### ISSUE THREAD

**Issue by rajiff** [reactivemanifesto/reactivemanifesto#117]
I think motivation is good, but if we could create a wiki page or a learning resource page, which has correct content for guiding the motivated souls will be effective

WWW is filled with so many content on this, but I feel each puts forwards its own interpretation and confusing the last one we might have red

**Comment by jboner** [comment]
I think this is the best book on the topic if one wants to dive deeper: https://www.manning.com/books/reactive-design-patterns
Written by @rkuhn.

**Comment by jboner** [comment]
@rajiff It would be great if you wanted to start a wiki or a web page with learning resources.  I don't think it is within the scope of the manifesto though. Thanks.
