### ISSUE TITLE
The `Parnas (1972)` link that appears in the Component Glossary section is no longer accessible 

### ISSUE THREAD

**Issue by rasummer** [reactivemanifesto/reactivemanifesto#118]
@jboner The `Parnas (1972)` link that appears in the [Component Glossary](https://github.com/reactivemanifesto/reactivemanifesto/blob/master/glossary.md#Component) section is no longer accessible https://www.cs.umd.edu/class/spring2003/cmsc838p/Design/criteria.pdf

**Comment by jboner** [comment]
Good catch. Here it is: http://repository.cmu.edu/cgi/viewcontent.cgi?article=2979&context=compsci

**Comment by rasummer** [comment]
Thanks, will update links across site and manifesto repo.

**Comment by jboner** [comment]
Can we close this one? @rasummer
