### ISSUE TITLE
Broken link in Glossary: Component

### ISSUE THREAD

**Issue by rolandweber** [reactivemanifesto/reactivemanifesto#127]
The glossary entry for [Component](https://www.reactivemanifesto.org/glossary#Component) references "Parnas (1972)". The underlying link redirects to https://kilthub.cmu.edu/, instead of a specific paper.

I suspect that the reference is about "On the Criteria To Be Used in Decomposing Systems into Modules", which I found here:
https://www.win.tue.nl/~wstomv/edu/2ip30/references/criteria_for_modularization.pdf

There's a different report with that title on the kilthub site, but from 1971 rather than 1972:
https://kilthub.cmu.edu/articles/On_the_criteria_to_be_used_in_decomposing_systems_into_modules/6607958

I guess the stable reference would be this one: https://dl.acm.org/citation.cfm?id=361623m
but the ACM doesn't provide a free download of the paper.

**Comment by rkuhn** [comment]
Thanks for noticing, fixed!

**Comment by rkuhn** [comment]
@jboner What is needed to get this deployed?

**Comment by jboner** [comment]
We need to wait for @rasummer to deploy the changes. They are across all translations right?

**Comment by rasummer** [comment]
I can take a look at porting this fix over to the website later in the week

**Comment by rkuhn** [comment]
Yes, I fixed all `glossary.*` files. Thanks @rasummer!

**Comment by rasummer** [comment]
This has been ported over to the website and is now live.
