### ISSUE TITLE
Sign the manifesto link from README should contain hash part

### ISSUE THREAD

**Issue by matmuchrapna** [reactivemanifesto/reactivemanifesto#45]
It is required for linking directly to "Sign the manifest" button.

**Comment by matmuchrapna** [comment]
polite ping =)

**Comment by rasummer** [comment]
@matmuchrapna thanks. Issue is on our radar.

**Comment by matmuchrapna** [comment]
@rasummer btw, where is manifest's site? I cannot find him oh gh-pages

**Comment by rasummer** [comment]
http://www.reactivemanifesto.org/

**Comment by matmuchrapna** [comment]
no-no, where is sources for the site? I will be able to fix it by myself, I will be able to create pull-request for this issue

**Comment by rasummer** [comment]
https://github.com/reactivemanifesto/website-manifesto

**Comment by matmuchrapna** [comment]
damn, site structure is too hard for me=(

**Comment by rasummer** [comment]
@matmuchrapna I guess what you'd like to do is have the 'sign the manifesto' link anchor to the actual 'sign the manifesto' button on the public site. This makes sense, and in one of the next updates I can add this.

**Comment by matmuchrapna** [comment]
yeah, you are right. It will be cool

**Comment by jboner** [comment]
Is this one fixed now? @rasummer

**Comment by rasummer** [comment]
Yes, an ID has been added to the site: http://www.reactivemanifesto.org/#sign-button that anchors directly to the sign button.

**Comment by matmuchrapna** [comment]
You are awesome, guys!
