### ISSUE TITLE
Please list the major authors of the manifesto

### ISSUE THREAD

**Issue by GrahamLea** [reactivemanifesto/reactivemanifesto#46]
It would be nice to know who wrote the Reactive Manifesto. I have heard some claim that this is just a vehicle for pushing people towards Akka, though I know that several non-Typesafe people have also contributed. Listing the major contributors would allow people to make up their own mind about whether this is a marketing exercise by one company or the consensus view of a broad range of specialists from across the industry. Greater transparency will either give more credence to the opinions therein or make it clear that this is mainly the work of some smart people in one or two companies. Either way, the community will benefit from that transparency.

I thought about doing a pull request based on the commit log, but I suspect a lot of the contribution has happened in emails and conversations rather than through GitHub. :)

**Comment by jboner** [comment]
Thanks for the suggestion. You are right. It is important. We will add authors. Stay tuned for next update.

**Comment by lazaridis-com** [comment]
This would be better achieve by a section for companies & institutions (see #47 )
