### ISSUE TITLE
Clarify that component boundaries are meant generically, not only for Software

### ISSUE THREAD

**Issue by rkuhn** [reactivemanifesto/reactivemanifesto#49]
The current text, especially of the Resilience part, is not clear enough on which level of abstraction or architectural granularity we mean, it can be misunderstood to prescribe exactly the Actor Model. While that model is a good fit for the software aspects—but by no means the only one!—we need to make it clear that hardware boundaries are equally important and that encapsulation of different services is a generic concern that can be addressed in several different ways.

**Comment by jboner** [comment]
Good point. Thanks. Where is the PR?

**Comment by jboner** [comment]
Perhaps link to a clarification in the glossary, where we can expand on the idea in more depth?

**Comment by rkuhn** [comment]
I’ll need to ponder this for some time: we need to fix the impression that first-time readers think we are talking only about Akka, and we’ll need to fix that on several levels.

**Comment by jboner** [comment]
I agree.

**Comment by lazaridis-com** [comment]
Independet of if the Resilience part describes Akka or not, the detail grade is too high and should be reduced.

**Comment by jboner** [comment]
@rkuhn What's the status on this?

**Comment by rkuhn** [comment]
Unfortunately I have not spent any time on this during the previous months. Given that the issue has been sitting here for more than two years, what is the public opinion on this matter? If there is a need to sharpen or otherwise improve the manifesto then it might be a good idea to hold a colloquium on the matter—somewhere in central Europe.

**Comment by jboner** [comment]
@rkuhn Should I close this issue?

**Comment by rkuhn** [comment]
Yes, it is unlikely that I’ll work on this and there does not seem to be anyone else pushing for it either.
