### ISSUE TITLE
clarify that Distribution vs. Simplicity is a trade-off that needs to be made consciously

### ISSUE THREAD

**Issue by rkuhn** [reactivemanifesto/reactivemanifesto#50]
We currently postulate that every system needs to value Resilience and Elasticity higher than simplicity or maintainability, but there are certainly many cases where avoiding the non-determinism that comes with distribution is more desirable than a few more 9’s in uptime. Most notably this is true for applications that are sufficiently available based on human intervention during office hours—internal services modeling business processes are an example.

Without diluting the point that _if you are forced by your requirements_ designing according to the Reactive principles is our clearly preferred approach, we should add that this force is relative and may be outweighed on a case by case basis. Consequences include applying Reactive at a more coarse-grained granularity or foregoing it entirely—as a conscious and well-educated decision.

**Comment by lazaridis-com** [comment]
As mentined in #49, I think the manifesto should be a general document (= should not go to much into detail).

**Comment by jboner** [comment]
@rkuhn What's the status on this?

**Comment by rkuhn** [comment]
Unfortunately I have not spent any time on this during the past months. It would be great to know whether this is an actual issue that needs to be addressed or whether we leave it like it is. How shall we find out?

**Comment by jboner** [comment]
@rkuhn Should I close this issue?

**Comment by rkuhn** [comment]
Hmm, my recent occupation has led me towards systems that benefit greatly from reactive design, but where data rates and a global audience are not the driving factors. But perhaps these topics are better discussed in blogs and articles than in the core text.
