### ISSUE TITLE
A grammar question

### ISSUE THREAD

**Issue by nasser-torabzade** [reactivemanifesto/reactivemanifesto#64]
Hi,
In first sentence of the manifesto, what does "look the same" refer to? "software" or "patterns"?
thanks.

**Comment by lazaridis-com** [comment]
> Organisations working in disparate domains are independently discovering patterns for building software that look the same.

The sentences reads like:

Different organizations working in different domains are independently discovering software-production-patterns that look the same.

**Comment by lazaridis-com** [comment]
@nasser-torabzade, @jboner, this issue can be closed i guess.

**Comment by jboner** [comment]
architecture-wise.
