### ISSUE TITLE
Event driven/centric is not bad and a message-driven-only system could be not resilient enough

### ISSUE THREAD

**Issue by Narvalex** [reactivemanifesto/reactivemanifesto#81]
Example: 2 endpoints. (E1 and E2)
Issue 1: E1 wants to talk to E2, but E2 its down.
MessageDrivenOnly: E1 will fail.
EventCentric: E1 will publish its desire as a durable event, and eventually E2 will get up and receive the payload, as a subscriber.

Issue 2: E2 needs all events that E1 published, but E2 was down for a long time. 
MessageDriven: E2 can request historical messages from E1, but what about the new messages that E1 is emmiting while E2 is reading old messages? Back pressure is not allowed. 
EventCentric: E2 gets all the events that happened E1, because E2 is always polling for new messages. E2 will be eventually consistent.

**Comment by lazaridis-com** [comment]
Solving #48 would negate this issue here.

**Comment by jboner** [comment]
It's not as simple as that. Most message-driven implementations would add a buffer on the sender and receiving side. This allows buffering of messages until the recipient comes back online. I think that what you are discussing is push vs pull. I agree that a pull approach can be better than a push approach, but it is orthogonal to the discussion about events vs messages. And just to make things clear: event-driven is not bad, it is a very useful abstraction, that can be layered on top of message-passing (the fabric, modeling communication) if the event-driven model needs to reach beyond its local scope. An event-driven model is often preferred as the end user API, as seen in pub/sub between microservices, event sourcing/CQRS, etc. But it is message-passing that makes it all tick, modeling distribution and communication. I discuss this at length in my recent (free) ebook: https://info.lightbend.com/ebook-reactive-microservices-the-evolution-of-microservices-at-scale-register.html

**Comment by Narvalex** [comment]
Thanks @jboner ! Why then do you contrast Message Driven to Event driven [here](https://www.reactivemanifesto.org/glossary#Message-Driven)?

**Comment by jboner** [comment]
Since they are very different models. Two models with different semantics, but that compose.
