### ISSUE TITLE
Chinese "Suggest improvements" link - 404 error

### ISSUE THREAD

**Issue by orangle** [reactivemanifesto/reactivemanifesto#86]
In the page  [http://www.reactivemanifesto.org/zh-CN](http://www.reactivemanifesto.org/zh-CN)  

[Suggest improvements](https://github.com/reactivemanifesto/reactivemanifesto/blob/master/README.zh-CN.md) is 404. 

And i think right link is [https://github.com/reactivemanifesto/reactivemanifesto/blob/master/README.zh-cn.md](https://github.com/reactivemanifesto/reactivemanifesto/blob/master/README.zh-cn.md)

**Comment by hepin1989** [comment]
refs https://github.com/reactivemanifesto/reactivemanifesto/pull/101

**Comment by jboner** [comment]
@rasummer Can you add the correct link to the zh-CN version?

**Comment by rasummer** [comment]
will do

**Comment by jboner** [comment]
Can this one be closed now? @rasummer

**Comment by rasummer** [comment]
Can we rename the file on this repo to uppercase (i will do this and send PR), as opposed to changing it over on the website. We are following a specific naming structure in the controllers and routes and it would be preferable to simply change the URL in this repo.
