### ISSUE TITLE
Visual for REACTIVE manifesto adoption needed

### ISSUE THREAD

**Issue by NicolasPAOLI** [reactivemanifesto/reactivemanifesto#89]
Hi all.
To arg about REACTIVE approach and it's adoption by people, I think it will be a good idea to represent that in a simple graphic.
We have actualy 16700 signed people but no idea of evolution of this number.
I think it wil be easy with the date and the number of signing people at this date.
Regards
Nico

**Comment by jboner** [comment]
Sounds like a great idea. But I think it would fit a blog post or article better than the actual manifesto. 

There is a REST API that you can hook in to. It can be pretty easily discovered by visiting the list page and using the browsers network tab to see what requests are made, basically the API is:

http://www.reactivemanifesto.org/signatories

And then in the response headers for that, there's a next link, that can be used to get the next page of results, and so on and so on.

If you prefer I can also send you a CSV file of the signatories. 

Thanks.

**Comment by NicolasPAOLI** [comment]
Thanks Jonas for your response.
Thanks for the API.
I'm interested by the csv to start modeling what information is pertinant to show. (Graph, period, etc.)
"REACTIVE Manifesto adoption" is it Hipe, good speed or loosing speed (oh no) ? I'll tel you the result.
Nico
