### ISSUE TITLE
Typo in German version, should be "September", not "Septempter"

### ISSUE THREAD

**Issue by lutzh** [reactivemanifesto/reactivemanifesto#90]
It seems the publishing date is not part of the actual text, so I can't fix it in a PR. On the German version of the site it says

"Veröffentlicht am 16. Septempter 2014 (v2.0)"

The word for the ninth month of the year is spelled September, not Septempter.

**Comment by rkuhn** [comment]
Funny typo! Since you found it, you may also open a PR against [the code in question](https://github.com/reactivemanifesto/website-manifesto/blob/master/conf/messages.de#L15).

**Comment by lutzh** [comment]
Done: https://github.com/reactivemanifesto/website-manifesto/pull/52
