### ISSUE TITLE
What can I do to deploy a translation to web?

### ISSUE THREAD

**Issue by qwefgh90** [reactivemanifesto/reactivemanifesto#93]
Hi,

Recently, I wrote a translation in Korean #91 . But, It's not deployed yet. It may be related to [website-manifesto](https://github.com/reactivemanifesto/website-manifesto)

Should I do something for deployment or not? Can I hear more information or process?

Thanks.

**Comment by qwefgh90** [comment]
@jboner If you don't mind, can you answer me?

**Comment by jboner** [comment]
We will deploy it. @rasummer is managing the deployment to the website. 

@rasummer, can you wrap up the new merged PRs and push it to the site? It's a bunch of fixes (German, Chinese), and this new Korean translation (manifesto + glossary). Perhaps something more that I'm forgetting.

**Comment by rasummer** [comment]
will do

**Comment by jboner** [comment]
@rasummer What's the status on this?

**Comment by rasummer** [comment]
@jboner @qwefgh90 I have the Korean scheduled in for early next week. However If I can slot it in this week I will. 

best

Richard

**Comment by jboner** [comment]
@rasummer Great. Thanks lot. Did you see the Chinese and German fixes?

**Comment by rasummer** [comment]
Yep, I take a look at all of the recent PR's and update the website

**Comment by qwefgh90** [comment]
I checked new Korean translation in the website.
@jboner  Thanks for the reply. I'll close this issue.
