### ISSUE TITLE
Change to Chinese version of RM

### ISSUE THREAD

**Issue by theotown** [reactivemanifesto/reactivemanifesto#96]
Please replace the word "Reactive" from “响应式” >>>>>>> to >>>>>> “反应式”

**Comment by zhenglaizhang** [comment]
Is there any specific reason to use `反应式` instead of `响应式`.
Searched via baidu (biggest Chinese SE), both are ok.

**Comment by hepin1989** [comment]
@theotown There is an ongoing translation/updating about the reactive manifesto, you could take a look at it, where we have replaced `响应式` with `反应式`。

We are currently translating the *Reactive Design Patterns* book, and these glossaries are the first thing to address:).

You could take a look at 

https://github.com/ReactivePlatform/reactivemanifesto/blob/master/glossary.zh-cn.md

@zhenglaizhang More not aligns right.

**Comment by hepin1989** [comment]
https://github.com/reactivemanifesto/reactivemanifesto/pull/101
